### ISSUE TITLE
can we update the codes for ansible 2.1.x?

### ISSUE THREAD

**Issue by SydOps** [nhsevidence/rancher-provisioning#2]
Running with vagrant up and vagrant provision, it always stop with some issues, seems it related with ansible version.

```
TASK [Pull and run Rancher server container] ***********************************
fatal: [172.19.8.100]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1975, in <module>\r\n    main()\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1945, in main\r\n    reloaded(manager, containers, count, name)\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1799, in reloaded\r\n    started(manager, containers, count, name)\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1776, in started\r\n    created = manager.create_containers(delta)\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1641, in create_containers\r\n    params['host_config'] = self.create_host_config()\r\n  File \"/tmp/ansible_wbBuXZ/ansible_module_docker.py\", line 1018, in create_host_config\r\n    return docker.utils.create_host_config(**params)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py\", line 403, in create_host_config\r\n    host_config['Binds'] = convert_volume_binds(binds)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py\", line 173, in convert_volume_binds\r\n    for k, v in binds.items():\r\nAttributeError: 'list' object has no attribute 'items'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

My guess is, the ansible codes work at v1.9.x, but not 2.x

**Comment by SydOps** [comment]
yes, I prove in ansible 1.9.6, it doesn't report the problem. 

Now I have a new error

```
TASK: [Add API access key to admin account] ***********************************
failed: [172.19.8.100] => {"failed": true, "parsed": false}
BECOME-SUCCESS-plnzuzkhyqqwfiqusorppyqknmleedlt
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1471127382.39-12109375116438/uri", line 2106, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1471127382.39-12109375116438/uri", line 415, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout, validate_certs)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1471127382.39-12109375116438/uri", line 311, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1592, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1334, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 854, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.19.8.100 closed.
```

**Comment by SydOps** [comment]
ic, this is a real old repo, which only updated to rancher 0.56.1

But the idea to combine server and agent into vagrant is good idea, and still useful. 

Let me see if I can update to latest (ansible, rancher server, rancher agent, etc)
